# ── Render functions ─────────────────────────────────────────────────────────
# Each render_* function writes a configuration file from the active palette.
# priority = 1 ensures renders always run before reloads (see reload.nix).
{
  priority = 1;

  functions = ''
    render_ghostty() {
      load_palette
      local out="$HOME/.config/ghostty/colors.conf"
      mkdir -p "$(dirname "$out")"
      cat > "$out" <<GHOSTTY_EOF
# Generated by palette-switch – do not edit by hand
palette = 0=$black
palette = 1=$danger
palette = 2=$success
palette = 3=$warning
palette = 4=$primary
palette = 5=$secondary
palette = 6=$info
palette = 7=$light
palette = 8=$muted
palette = 9=$danger
palette = 10=$success
palette = 11=$warning
palette = 12=$primary
palette = 13=$secondary
palette = 14=$info
palette = 15=$white
background = $programBg
foreground = $fg
cursor-color = $accent
cursor-text = $fg
selection-background = $muted
selection-foreground = $fg
GHOSTTY_EOF
      log "Rendered Ghostty colors → $out"
    }

    render_waybar() {
      load_palette
      local css_dir="$HOME/.config/waybar"
      mkdir -p "$css_dir"
      cat > "$css_dir/normal-style.css" <<CSS_EOF
/* Generated by palette-switch – do not edit by hand */

window#waybar {
  background-color: $bg;
  color: $fg;
  border: 5px solid $primary;
  border-top: hidden;
  border-radius: 0px 0px 30px 30px;
}

box {
  transition: 1s;
  margin-top: 0px;
}

label.module {
  margin: 10px 10px;
  transition: 1s;
}

#custom-spacer {
  padding: 0px 30px;
}

@keyframes drop {
  from { margin-top: 0; }
  to   { margin-top: 300px; }
}

.module {
  margin-top: 0px;
  animation: 0.05s linear drop;
  background-color: $secondary;
}
CSS_EOF
      log "Rendered Waybar CSS → $css_dir/normal-style.css"

      # Ensure style.css points somewhere sensible
      local style="$css_dir/style.css"
      local moved="$css_dir/moved-style.css"
      if [[ -L "$style" && "$(readlink "$style")" == *"moved-style.css"* && -e "$moved" ]]; then
        : # keep pointing at moved-style.css
      else
        ln -sf "$css_dir/normal-style.css" "$style"
      fi
    }

    render_hyprland() {
      load_palette
      local out="$HOME/.config/hypr/palette-colors.conf"
      mkdir -p "$(dirname "$out")"
      # Strip leading '#' for Hyprland's rgb() format
      local bg_hex fg_hex primary_hex secondary_hex tertiary_hex muted_hex danger_hex
      bg_hex=$(echo "$bg" | tr -d '#')
      fg_hex=$(echo "$fg" | tr -d '#')
      primary_hex=$(echo "$primary" | tr -d '#')
      secondary_hex=$(echo "$secondary" | tr -d '#')
      tertiary_hex=$(echo "$tertiary" | tr -d '#')
      muted_hex=$(echo "$muted" | tr -d '#')
      danger_hex=$(echo "$danger" | tr -d '#')
      cat > "$out" <<HYPR_EOF
# Generated by palette-switch – do not edit by hand
\$paletteBg        = rgb($bg_hex)
\$paletteFg        = rgb($fg_hex)
\$palettePrimary   = rgb($primary_hex)
\$paletteSecondary = rgb($secondary_hex)
\$paletteTertiary  = rgb($tertiary_hex)
\$paletteMuted     = rgb($muted_hex)
\$paletteDanger    = rgb($danger_hex)
HYPR_EOF
      log "Rendered Hyprland palette → $out"
    }

    render_neovim() {
      load_palette
      local out="$HOME/.config/nvim/lua/palette-colors.lua"
      mkdir -p "$(dirname "$out")"
      cat > "$out" <<LUA_EOF
-- Generated by palette-switch – do not edit by hand
-- Add  require('palette-colors').apply()  to your init.lua to use these colors
local M = {}

M.colors = {
  bg           = "$bg",
  programBg    = "$programBg",
  fg           = "$fg",
  primary      = "$primary",
  secondary    = "$secondary",
  tertiary     = "$tertiary",
  accent       = "$accent",
  danger       = "$danger",
  warning      = "$warning",
  success      = "$success",
  info         = "$info",
  black        = "$black",
  dark         = "$dark",
  muted        = "$muted",
  light        = "$light",
  white        = "$white",
}

function M.apply()
  local c = M.colors
  vim.api.nvim_set_hl(0, "Normal",      { fg = c.fg,      bg = c.bg })
  vim.api.nvim_set_hl(0, "NormalFloat", { fg = c.fg,      bg = c.programBg })
  vim.api.nvim_set_hl(0, "Comment",     { fg = c.muted,   italic = true })
  vim.api.nvim_set_hl(0, "Keyword",     { fg = c.primary, bold   = true })
  vim.api.nvim_set_hl(0, "Function",    { fg = c.secondary })
  vim.api.nvim_set_hl(0, "String",      { fg = c.success })
  vim.api.nvim_set_hl(0, "Number",      { fg = c.warning })
  vim.api.nvim_set_hl(0, "Error",       { fg = c.danger,  bold   = true })
  vim.api.nvim_set_hl(0, "StatusLine",  { fg = c.fg,      bg = c.dark })
  vim.api.nvim_set_hl(0, "LineNr",      { fg = c.muted })
  vim.api.nvim_set_hl(0, "CursorLine",  { bg = c.dark })
  vim.api.nvim_set_hl(0, "Visual",      { bg = c.muted })
  vim.api.nvim_set_hl(0, "Pmenu",       { fg = c.fg,      bg = c.programBg })
  vim.api.nvim_set_hl(0, "PmenuSel",    { fg = c.bg,      bg = c.primary })
end

return M
LUA_EOF
      log "Rendered Neovim palette → $out"
    }

    render_wofi() {
      load_palette
      local css_dir="$HOME/.config/wofi"
      mkdir -p "$css_dir"
      cat > "$css_dir/style.css" <<CSS_EOF
/* Generated by palette-switch – do not edit by hand */

@keyframes pri-sec-gradient-bg {
  0% {
    background-color: $primary;
  }
  50% {
    background-color: $secondary;
  }
  100% {
    background-color: $primary;
  }
}

window {
  background-color: $programBg;
  color: $fg;
  border: 3px solid $primary;
  border-radius: 12px;
  padding: 10px;
}

#input {
  background-color: $programBg;
  color: $fg;
  border: 3px solid $primary;
  border-radius: 8px;
  padding: 6px;
}

#entry:selected {
  color: $programBg;
  animation: 6s infinite linear pri-sec-gradient-bg;
  transition: background-color 0.5s ease;
}

#entry {
  padding: 4px 6px;
  background-color: transparent;
}
CSS_EOF
      log "Rendered Wofi CSS → $css_dir/style.css"
    }

    render_vscode() {
      load_palette
      # Two-file approach:
      #   settings.base.json  – nix-store symlink managed by home.nix;
      #                         contains all static (non-color) settings.
      #   settings.colors.json – mutable file managed by this function;
      #                          contains only the two color blocks.
      #   settings.json        – mutable file, merged from the two above;
      #                          never owned by home-manager so there is
      #                          no checkLinkTargets conflict.
      local vscode_dir="$HOME/.config/Code/User"
      local base_file="$vscode_dir/settings.base.json"
      local colors_file="$vscode_dir/settings.colors.json"
      local settings_file="$vscode_dir/settings.json"
      mkdir -p "$vscode_dir"

      # Write the color blocks to the dedicated colors file.
      local tmp_colors
      tmp_colors=$(mktemp)
      jq -n \
        --arg bg        "$bg"        \
        --arg programBg "$programBg" \
        --arg fg        "$fg"        \
        --arg primary   "$primary"   \
        --arg secondary "$secondary" \
        --arg tertiary  "$tertiary"  \
        --arg accent    "$accent"    \
        --arg danger    "$danger"    \
        --arg warning   "$warning"   \
        --arg success   "$success"   \
        --arg info      "$info"      \
        --arg dark      "$dark"      \
        --arg muted     "$muted"     \
        --arg white     "$white"     \
        '{
          "workbench.colorCustomizations": {
            "editor.background":                  $bg,
            "editor.foreground":                  $fg,
            "editor.lineHighlightBackground":     $dark,
            "editor.selectionBackground":         $muted,
            "editorCursor.foreground":            $accent,
            "editorLineNumber.foreground":        $muted,
            "editorLineNumber.activeForeground":  $fg,
            "editorIndentGuide.background1":      $muted,
            "editorGroupHeader.tabsBackground":   $programBg,
            "tab.activeBackground":               $dark,
            "tab.inactiveBackground":             $programBg,
            "tab.activeForeground":               $fg,
            "tab.inactiveForeground":             $muted,
            "activityBar.background":             $programBg,
            "activityBar.foreground":             $fg,
            "activityBar.activeBorder":           $primary,
            "sideBar.background":                 $programBg,
            "sideBar.foreground":                 $fg,
            "sideBarTitle.foreground":            $primary,
            "statusBar.background":               $dark,
            "statusBar.foreground":               $fg,
            "statusBar.noFolderBackground":       $dark,
            "titleBar.activeBackground":          $programBg,
            "titleBar.activeForeground":          $fg,
            "titleBar.inactiveBackground":        $programBg,
            "panel.background":                   $programBg,
            "panelTitle.activeForeground":        $primary,
            "terminal.background":                $bg,
            "terminal.foreground":                $fg,
            "terminal.ansiBlack":                 $dark,
            "terminal.ansiRed":                   $danger,
            "terminal.ansiGreen":                 $success,
            "terminal.ansiYellow":                $warning,
            "terminal.ansiBlue":                  $primary,
            "terminal.ansiMagenta":               $secondary,
            "terminal.ansiCyan":                  $info,
            "terminal.ansiWhite":                 $white,
            "focusBorder":                        $primary,
            "selection.background":               $muted,
            "input.background":                   $programBg,
            "input.foreground":                   $fg,
            "input.border":                       $muted,
            "inputOption.activeBorder":           $primary,
            "list.activeSelectionBackground":     $dark,
            "list.activeSelectionForeground":     $fg,
            "list.hoverBackground":               $dark,
            "scrollbarSlider.background":         $muted,
            "scrollbarSlider.hoverBackground":    $primary,
            "button.background":                  $primary,
            "button.foreground":                  $bg,
            "badge.background":                   $primary,
            "badge.foreground":                   $bg,
            "progressBar.background":             $primary
          },
          "editor.tokenColorCustomizations": {
            "textMateRules": [
              {
                "name": "Comment",
                "scope": ["comment", "punctuation.definition.comment"],
                "settings": { "foreground": $muted, "fontStyle": "italic" }
              },
              {
                "name": "Keyword",
                "scope": ["keyword", "storage.type", "storage.modifier"],
                "settings": { "foreground": $primary, "fontStyle": "bold" }
              },
              {
                "name": "Function",
                "scope": ["entity.name.function", "support.function"],
                "settings": { "foreground": $secondary }
              },
              {
                "name": "String",
                "scope": ["string", "string.quoted"],
                "settings": { "foreground": $success }
              },
              {
                "name": "Number",
                "scope": ["constant.numeric"],
                "settings": { "foreground": $warning }
              },
              {
                "name": "Type",
                "scope": ["entity.name.type", "support.type"],
                "settings": { "foreground": $tertiary }
              },
              {
                "name": "Variable",
                "scope": ["variable", "variable.other"],
                "settings": { "foreground": $fg }
              }
            ]
          }
        }' > "$tmp_colors"
      mv "$tmp_colors" "$colors_file"
      log "Rendered VSCode colors → $colors_file"

      # Merge base settings + color settings into the final settings.json.
      # settings.json is NOT owned by home-manager so there is no
      # checkLinkTargets conflict; it is always a plain mutable file.
      local tmp_merged
      tmp_merged=$(mktemp)
      if [[ -e "$base_file" ]]; then
        if ! jq -s '.[0] * .[1]' "$base_file" "$colors_file" > "$tmp_merged"; then
          log_err "Failed to merge base+colors settings; falling back to colors only"
          cp "$colors_file" "$tmp_merged"
        fi
      else
        log_err "settings.base.json not found; rebuild home-manager to regenerate it"
        cp "$colors_file" "$tmp_merged"
      fi
      mv "$tmp_merged" "$settings_file"
      log "Rendered VSCode settings → $settings_file (base + colors merged)"
    }

    render_palette_css() {
      local out="$PALETTES_DIR/palette.css"
      if [[ ! -f "$ACTIVE_LINK" ]]; then
        log_err "No active palette found at $ACTIVE_LINK"
        return 1
      fi
      local tmp_css
      tmp_css=$(mktemp)
      {
        printf '/* Generated by palette-switch – do not edit by hand */\n'
        printf ':root {\n'
        jq -r 'to_entries | .[] | "  --\(.key): \(.value);"' "$ACTIVE_LINK"
        printf '}\n'
      } > "$tmp_css"
      mv "$tmp_css" "$out"
      log "Rendered palette CSS → $out"
    }

    render_wallpaper() {
      local source_file="$HOME/.config/palettes/wallpaper-source.png"
      local out="$HOME/.local/share/wallpaper.png"
      if [[ ! -f "$source_file" ]]; then
        log "No wallpaper source at $source_file – skipping"
        log "(place a PNG there to enable palette-coloured wallpapers)"
        return 0
      fi
      if palette-wallpaper "$source_file" "$out"; then
        log "Rendered wallpaper → $out"
      else
        log_err "palette-wallpaper failed – check that $source_file is a valid PNG"
        return 1
      fi
    }
  '';

  apply = ''
    render_ghostty     || log_err "Ghostty render failed"
    render_waybar      || log_err "Waybar render failed"
    render_hyprland    || log_err "Hyprland render failed"
    render_neovim      || log_err "Neovim render failed"
    render_wofi        || log_err "Wofi render failed"
    render_vscode      || log_err "VSCode render failed"
    render_palette_css || log_err "Palette CSS render failed"
    render_wallpaper   || true
  '';
}
