# ── XCursor render + reload functions ────────────────────────────────────────
# render_xcursor  – reads ~/.config/xcursor/config.json (written by the xcursor
#                   home-manager module), substitutes palette colour placeholders
#                   in the base-theme SVGs, converts them to PNGs via
#                   rsvg-convert, and assembles binary XCursor files with
#                   xcursorgen.  The generated theme lands at
#                   ~/.local/share/icons/palette-cursor/.
# reload_xcursor  – applies the freshly-generated theme to the running session
#                   via hyprctl setcursor and updates GTK3/GTK4 settings files.
#
# Both functions silently skip when their prerequisites are absent (config
# file, rsvg-convert, xcursorgen), so this script file is safe to include
# even on systems where the xcursor module is not enabled.
#
# priority = 1 keeps render + reload together and ensures cursors are ready
# before the compositor reload in reload.nix (priority = 2).
{
  priority = 1;

  functions = ''
    render_xcursor() {
      local config_file="$HOME/.config/xcursor/config.json"
      if [[ ! -f "$config_file" ]]; then
        log "XCursor: config not found at $config_file – skipping"
        return 0
      fi

      if ! command -v rsvg-convert > /dev/null 2>&1; then
        log_err "XCursor: rsvg-convert not found (install librsvg)"
        return 1
      fi
      if ! command -v xcursorgen > /dev/null 2>&1; then
        log_err "XCursor: xcursorgen not found (install xorg.xcursorgen)"
        return 1
      fi

      local base_theme cursor_size
      base_theme=$(jq -r '.baseTheme // "default"' "$config_file")
      cursor_size=$(jq -r '.size // 24'             "$config_file")

      local base_dir="$HOME/.local/share/xcursor-bases/$base_theme"
      if [[ ! -d "$base_dir/svgs" ]]; then
        log_err "XCursor: base theme '$base_theme' not found at $base_dir/svgs"
        return 1
      fi

      load_palette

      local out_dir="$HOME/.local/share/icons/palette-cursor"
      local cursors_dir="$out_dir/cursors"
      # Remove stale cursors so deleted/renamed SVGs do not linger
      rm -rf "$cursors_dir"
      mkdir -p "$cursors_dir"

      # Minimal index.theme required by GTK / icon-theme lookup
      cat > "$out_dir/index.theme" <<THEME_EOF
[Icon Theme]
Name=palette-cursor
Comment=Palette-driven cursor theme (generated by palette-switch)
THEME_EOF

      local hotspots_file="$base_dir/hotspots.json"
      local tmp_dir
      tmp_dir=$(mktemp -d)

      # ── Process each SVG in the base theme ─────────────────────────────────
      for svg_file in "$base_dir/svgs/"*.svg; do
        [[ -f "$svg_file" ]] || continue
        local cursor_name
        cursor_name=$(basename "$svg_file" .svg)

        # Substitute every colour placeholder with the active palette value
        local tmp_svg="$tmp_dir/$cursor_name.svg"
        sed \
          -e "s|@@PRIMARY@@|$primary|g"     \
          -e "s|@@SECONDARY@@|$secondary|g" \
          -e "s|@@BG@@|$bg|g"               \
          -e "s|@@FG@@|$fg|g"               \
          -e "s|@@ACCENT@@|$accent|g"       \
          -e "s|@@MUTED@@|$muted|g"         \
          -e "s|@@DANGER@@|$danger|g"       \
          -e "s|@@WARNING@@|$warning|g"     \
          -e "s|@@SUCCESS@@|$success|g"     \
          -e "s|@@INFO@@|$info|g"           \
          "$svg_file" > "$tmp_svg"

        # Retrieve hotspot for this cursor (stored for the 32×32 base size)
        local xhot yhot
        if [[ -f "$hotspots_file" ]]; then
          xhot=$(jq -r --arg n "$cursor_name" '.[$n][0] // 0' "$hotspots_file")
          yhot=$(jq -r --arg n "$cursor_name" '.[$n][1] // 0' "$hotspots_file")
        else
          xhot=0
          yhot=0
        fi

        # Generate PNG + xcursorgen config at four standard sizes
        local cfg_file="$tmp_dir/$cursor_name.cfg"
        : > "$cfg_file"
        for size in 24 32 48 64; do
          # Scale hotspot proportionally from the 32-px design baseline
          local scaled_xhot scaled_yhot
          scaled_xhot=$(( xhot * size / 32 ))
          scaled_yhot=$(( yhot * size / 32 ))
          local tmp_png="$tmp_dir/${cursor_name}_${size}.png"
          rsvg-convert -w "$size" -h "$size" "$tmp_svg" -o "$tmp_png"
          # xcursorgen config line: <size> <xhot> <yhot> <filename> <frame-delay-ms>
          # Frame delay (50 ms) is required for animated cursors; for static cursors
          # (single frame) the field is mandatory but the value is ignored.
          echo "$size $scaled_xhot $scaled_yhot ${cursor_name}_${size}.png 50" >> "$cfg_file"
        done

        # Assemble all sizes into a single binary XCursor file
        (cd "$tmp_dir" && xcursorgen "$cfg_file" "$cursors_dir/$cursor_name")
      done

      # ── Install cursor name aliases ─────────────────────────────────────────
      local aliases_file="$base_dir/aliases"
      if [[ -f "$aliases_file" ]]; then
        while IFS= read -r line; do
          # Strip leading/trailing whitespace; skip blank lines and comments
          line="${line#"${line%%[![:space:]]*}"}"
          [[ -z "$line" || "$line" == "#"* ]] && continue
          local alias_name target_name
          alias_name="${line%%=*}"
          target_name="${line#*=}"
          # Trim whitespace
          alias_name="${alias_name%"${alias_name##*[![:space:]]}"}"
          target_name="${target_name%"${target_name##*[![:space:]]}"}"
          [[ -z "$alias_name" || -z "$target_name" ]] && continue
          local target_cursor="$cursors_dir/$target_name"
          if [[ -f "$target_cursor" ]]; then
            ln -sf "$target_name" "$cursors_dir/$alias_name"
          fi
        done < "$aliases_file"
      fi

      rm -rf "$tmp_dir"
      log "XCursor: generated palette-cursor (base: $base_theme, size: ${cursor_size}px)"
    }

    # Helper: update (or create) a GTK settings.ini with the palette-cursor
    # theme name and size, without touching unrelated settings.
    _xcursor_update_gtk_settings() {
      local settings_file="$1" cursor_size="$2"
      local dir
      dir=$(dirname "$settings_file")
      mkdir -p "$dir"
      if [[ -f "$settings_file" ]]; then
        if grep -q "gtk-cursor-theme-name" "$settings_file"; then
          sed -i "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=palette-cursor/" "$settings_file"
        else
          echo "gtk-cursor-theme-name=palette-cursor" >> "$settings_file"
        fi
        if grep -q "gtk-cursor-theme-size" "$settings_file"; then
          sed -i "s/gtk-cursor-theme-size=.*/gtk-cursor-theme-size=$cursor_size/" "$settings_file"
        else
          echo "gtk-cursor-theme-size=$cursor_size" >> "$settings_file"
        fi
      else
        printf '[Settings]\ngtk-cursor-theme-name=palette-cursor\ngtk-cursor-theme-size=%s\n' \
          "$cursor_size" > "$settings_file"
      fi
      log "XCursor: updated $(basename "$dir") cursor settings"
    }

    reload_xcursor() {
      local config_file="$HOME/.config/xcursor/config.json"
      [[ -f "$config_file" ]] || return 0

      local cursor_size
      cursor_size=$(jq -r '.size // 24' "$config_file")

      # ── Apply via Hyprland ────────────────────────────────────────────────
      if command -v hyprctl > /dev/null 2>&1 && hyprctl version > /dev/null 2>&1; then
        if hyprctl setcursor palette-cursor "$cursor_size"; then
          log "XCursor: applied via hyprctl setcursor (size: ${cursor_size})"
        else
          log_err "XCursor: hyprctl setcursor failed"
        fi
      else
        log "XCursor: Hyprland not running – skipping hyprctl setcursor"
      fi

      _xcursor_update_gtk_settings "$HOME/.config/gtk-3.0/settings.ini" "$cursor_size"
      _xcursor_update_gtk_settings "$HOME/.config/gtk-4.0/settings.ini" "$cursor_size"
    }
  '';

  apply = ''
    render_xcursor || log_err "XCursor render failed"
    reload_xcursor || log_err "XCursor reload failed"
  '';
}
