# ── XCursor render + reload functions ────────────────────────────────────────
# render_xcursor  – reads ~/.config/xcursor/config.json (written by the xcursor
#                   home-manager module), substitutes palette colour placeholders
#                   in the base-theme SVGs, converts them to PNGs via
#                   rsvg-convert, and assembles binary XCursor files with
#                   xcursorgen.  A unique timestamp-based theme name is used on
#                   every render (e.g. palette-cursor-1711468203) so that
#                   Hyprland never serves a cached copy and always re-reads the
#                   new files from disk.  The active name is written to
#                   ~/.config/xcursor/active-theme for reload_xcursor to read.
#                   Old palette-cursor-* dirs are removed after each render.
# reload_xcursor  – reads the active theme name from the state file, applies it
#                   via hyprctl setcursor, updates GTK3/GTK4 settings.ini, and
#                   notifies running GTK4 apps via gsettings.
#
# Both functions silently skip when their prerequisites are absent (config
# file, rsvg-convert, xcursorgen), so this script file is safe to include
# even on systems where the xcursor module is not enabled.
#
# priority = 1 keeps render + reload together and ensures cursors are ready
# before the compositor reload in reload.nix (priority = 2).
{
  priority = 1;

  functions = ''
        render_xcursor() {
          local config_file="$HOME/.config/xcursor/config.json"
          if [[ ! -f "$config_file" ]]; then
            log "XCursor: config not found at $config_file – skipping"
            return 0
          fi

          if ! command -v rsvg-convert > /dev/null 2>&1; then
            log_err "XCursor: rsvg-convert not found (install librsvg)"
            return 1
          fi
          if ! command -v xcursorgen > /dev/null 2>&1; then
            log_err "XCursor: xcursorgen not found (install xorg.xcursorgen)"
            return 1
          fi

          local base_theme cursor_size
          base_theme=$(jq -r '.baseTheme // "default"' "$config_file")
          cursor_size=$(jq -r '.size // 24'             "$config_file")

          local base_dir="$HOME/.local/share/xcursor-bases/$base_theme"
          if [[ ! -d "$base_dir/svgs" ]]; then
            log_err "XCursor: base theme '$base_theme' not found at $base_dir/svgs"
            return 1
          fi

          load_palette

          # Use a unique, timestamp-based theme name on every render.
          # Hyprland caches themes by name internally, so reusing "palette-cursor"
          # means it never re-reads the newly generated files from disk.
          # A fresh name on every run guarantees a cache-miss and a real disk read.
          local theme_name
          theme_name="palette-cursor-$(date +%s)"
          local out_dir="$HOME/.local/share/icons/$theme_name"
          local cursors_dir="$out_dir/cursors"
          mkdir -p "$cursors_dir"

          # Minimal index.theme required by GTK / icon-theme lookup
          cat > "$out_dir/index.theme" <<THEME_EOF
    [Icon Theme]
    Name=$theme_name
    Comment=Palette-driven cursor theme (generated by palette-switch)
    THEME_EOF

          local hotspots_file="$base_dir/hotspots.json"
          local tmp_dir
          tmp_dir=$(mktemp -d)

          # ── Process each SVG in the base theme ─────────────────────────────────
          for svg_file in "$base_dir/svgs/"*.svg; do
            [[ -f "$svg_file" ]] || continue
            local cursor_name
            cursor_name=$(basename "$svg_file" .svg)

            # Substitute every colour placeholder with the active palette value
            local tmp_svg="$tmp_dir/$cursor_name.svg"
            sed \
              -e "s|@@PRIMARY@@|$primary|g"     \
              -e "s|@@SECONDARY@@|$secondary|g" \
              -e "s|@@BG@@|$bg|g"               \
              -e "s|@@FG@@|$fg|g"               \
              -e "s|@@ACCENT@@|$accent|g"       \
              -e "s|@@MUTED@@|$muted|g"         \
              -e "s|@@DANGER@@|$danger|g"       \
              -e "s|@@WARNING@@|$warning|g"     \
              -e "s|@@SUCCESS@@|$success|g"     \
              -e "s|@@INFO@@|$info|g"           \
              -e "s|@@WHITE@@|$white|g"           \
              "$svg_file" > "$tmp_svg"

            # Retrieve hotspot for this cursor (stored for the 32×32 base size)
            local xhot yhot
            if [[ -f "$hotspots_file" ]]; then
              xhot=$(jq -r --arg n "$cursor_name" '.[$n][0] // 0' "$hotspots_file")
              yhot=$(jq -r --arg n "$cursor_name" '.[$n][1] // 0' "$hotspots_file")
            else
              xhot=0
              yhot=0
            fi

            # Generate PNG + xcursorgen config at four standard sizes
            local cfg_file="$tmp_dir/$cursor_name.cfg"
            : > "$cfg_file"
            for size in 24 32 48 64; do
              # Scale hotspot proportionally from the 32-px design baseline
              local scaled_xhot scaled_yhot
              scaled_xhot=$(( xhot * size / 32 ))
              scaled_yhot=$(( yhot * size / 32 ))
              local tmp_png="$tmp_dir/''${cursor_name}_''${size}.png"
              rsvg-convert -w "$size" -h "$size" "$tmp_svg" -o "$tmp_png"
              # xcursorgen config line: <size> <xhot> <yhot> <filename> <frame-delay-ms>
              # Frame delay (50 ms) is required for animated cursors; for static cursors
              # (single frame) the field is mandatory but the value is ignored.
              echo "$size $scaled_xhot $scaled_yhot ''${cursor_name}_''${size}.png 50" >> "$cfg_file"
            done

            # Assemble all sizes into a single binary XCursor file
            (cd "$tmp_dir" && xcursorgen "$cfg_file" "$cursors_dir/$cursor_name")
          done

          # ── Install cursor name aliases ─────────────────────────────────────────
          local aliases_file="$base_dir/aliases"
          if [[ -f "$aliases_file" ]]; then
            # Filter out blank lines and comment lines, then split on '='
            while IFS='=' read -r alias_name target_name; do
              [[ -z "$alias_name" || -z "$target_name" ]] && continue
              local target_cursor="$cursors_dir/$target_name"
              if [[ -f "$target_cursor" ]]; then
                ln -sf "$target_name" "$cursors_dir/$alias_name"
              fi
            done < <(grep -v '^[[:space:]]*#' "$aliases_file" | grep -v '^[[:space:]]*$' | grep '=')
          fi

          rm -rf "$tmp_dir"

          # Persist the active theme name so reload_xcursor knows which directory to apply.
          local state_file="$HOME/.config/xcursor/active-theme"
          mkdir -p "$(dirname "$state_file")"
          echo "$theme_name" > "$state_file"

          # Keep a stable "palette-cursor" symlink in BOTH standard search paths:
          #
          # 1. ~/.local/share/icons/  – XDG-compliant path, used by modern GTK,
          #    libxcursor >= 0.9.0, and compositor lookup (hyprctl setcursor).
          #
          # 2. ~/.icons/              – traditional legacy path checked by
          #    libxcursor, Chromium/Electron (VSCode), and many older X11 apps
          #    that do NOT follow XDG.  Without this symlink VSCode cannot find
          #    the theme regardless of XCURSOR_THEME being set correctly.
          local icons_dir="$HOME/.local/share/icons"
          ln -sfn "$icons_dir/$theme_name" "$icons_dir/palette-cursor"

          mkdir -p "$HOME/.icons"
          ln -sfn "$icons_dir/$theme_name" "$HOME/.icons/palette-cursor"

          # Remove all previous palette-cursor-* theme directories to avoid accumulation.
          for old_dir in "$icons_dir/palette-cursor-"*/; do
            [[ -d "$old_dir" ]] || continue
            [[ "$old_dir" == "$out_dir/" ]] && continue
            rm -rf "$old_dir"
          done

          log "XCursor: generated $theme_name (base: $base_theme, size: ''${cursor_size}px)"
        }

        # Helper: update (or create) a GTK settings.ini with the given cursor
        # theme name and size, without touching unrelated settings.
        _xcursor_update_gtk_settings() {
          local settings_file="$1" cursor_size="$2" theme_name="$3"
          local dir
          dir=$(dirname "$settings_file")
          mkdir -p "$dir"
          if [[ -f "$settings_file" ]]; then
            if grep -q "gtk-cursor-theme-name" "$settings_file"; then
              sed -i "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=$theme_name/" "$settings_file"
            else
              echo "gtk-cursor-theme-name=$theme_name" >> "$settings_file"
            fi
            if grep -q "gtk-cursor-theme-size" "$settings_file"; then
              sed -i "s/gtk-cursor-theme-size=.*/gtk-cursor-theme-size=$cursor_size/" "$settings_file"
            else
              echo "gtk-cursor-theme-size=$cursor_size" >> "$settings_file"
            fi
          else
            printf '[Settings]\ngtk-cursor-theme-name=%s\ngtk-cursor-theme-size=%s\n' \
              "$theme_name" "$cursor_size" > "$settings_file"
          fi
          log "XCursor: updated $(basename "$dir") cursor settings"
        }

        reload_xcursor() {
          local config_file="$HOME/.config/xcursor/config.json"
          [[ -f "$config_file" ]] || return 0

          local cursor_size
          cursor_size=$(jq -r '.size // 24' "$config_file")

          # Determine the unique theme name written by render_xcursor.
          local state_file="$HOME/.config/xcursor/active-theme"
          if [[ ! -f "$state_file" ]]; then
            log_err "XCursor: active-theme state file not found – run palette-switch first"
            return 0
          fi
          local theme_name
          theme_name=$(cat "$state_file")

          # ── Apply via Hyprland ────────────────────────────────────────────────
          if command -v hyprctl > /dev/null 2>&1 && hyprctl version > /dev/null 2>&1; then
            if hyprctl setcursor "$theme_name" "$cursor_size"; then
              log "XCursor: applied $theme_name via hyprctl setcursor (size: ''${cursor_size})"
            else
              log_err "XCursor: hyprctl setcursor failed"
            fi
          else
            log "XCursor: Hyprland not running – skipping hyprctl setcursor"
          fi

          _xcursor_update_gtk_settings "$HOME/.config/gtk-3.0/settings.ini" "$cursor_size" "palette-cursor"
          _xcursor_update_gtk_settings "$HOME/.config/gtk-4.0/settings.ini" "$cursor_size" "palette-cursor"

          # Notify running GTK4 applications via gsettings so they pick up the new cursor.
          # The stable "palette-cursor" symlink (updated by render_xcursor) resolves to
          # the freshly generated theme directory, so running apps see the new colours.
          if command -v gsettings > /dev/null 2>&1; then
            gsettings set org.gnome.desktop.interface cursor-theme "palette-cursor" 2>/dev/null || true
            gsettings set org.gnome.desktop.interface cursor-size  "$cursor_size"   2>/dev/null || true
          fi
        }
  '';

  apply = ''
    render_xcursor || log_err "XCursor render failed"
    reload_xcursor || log_err "XCursor reload failed"
  '';
}
