# palette-switch module: ghostty
# Rendered and sourced automatically by palette-switch.

PALETTE_SWITCH_RENDERERS+=(ghostty)

render_ghostty() {
  load_palette
  local out="$HOME/.config/ghostty/colors.conf"
  mkdir -p "$(dirname "$out")"
  cat > "$out" <<GHOSTTY_EOF
# Generated by palette-switch – do not edit by hand
palette = 0=$black
palette = 1=$danger
palette = 2=$success
palette = 3=$warning
palette = 4=$primary
palette = 5=$secondary
palette = 6=$info
palette = 7=$light
palette = 8=$muted
palette = 9=$danger
palette = 10=$success
palette = 11=$warning
palette = 12=$primary
palette = 13=$secondary
palette = 14=$info
palette = 15=$white
background = $programBg
foreground = $fg
cursor-color = $accent
cursor-text = $fg
selection-background = $muted
selection-foreground = $fg
GHOSTTY_EOF
  log "Rendered Ghostty colors → $out"
}

reload_ghostty() {
  if pgrep ghostty > /dev/null 2>&1; then
    if pkill -SIGUSR2 ghostty; then
      log "Reloaded Ghostty"
    else
      log_err "Failed to signal Ghostty"
    fi
  else
    log "Ghostty not running – skipping reload"
  fi
}
