# palette-switch module: hyprland
# Rendered and sourced automatically by palette-switch.

PALETTE_SWITCH_RENDERERS+=(hyprland)

render_hyprland() {
  load_palette
  local out="$HOME/.config/hypr/palette-colors.conf"
  mkdir -p "$(dirname "$out")"
  # Strip leading '#' for Hyprland's rgb() format
  local bg_hex fg_hex primary_hex secondary_hex tertiary_hex muted_hex danger_hex
  bg_hex=$(echo "$bg" | tr -d '#')
  fg_hex=$(echo "$fg" | tr -d '#')
  primary_hex=$(echo "$primary" | tr -d '#')
  secondary_hex=$(echo "$secondary" | tr -d '#')
  tertiary_hex=$(echo "$tertiary" | tr -d '#')
  muted_hex=$(echo "$muted" | tr -d '#')
  danger_hex=$(echo "$danger" | tr -d '#')
  cat > "$out" <<HYPR_EOF
# Generated by palette-switch – do not edit by hand
\$paletteBg        = rgb($bg_hex)
\$paletteFg        = rgb($fg_hex)
\$palettePrimary   = rgb($primary_hex)
\$paletteSecondary = rgb($secondary_hex)
\$paletteTertiary  = rgb($tertiary_hex)
\$paletteMuted     = rgb($muted_hex)
\$paletteDanger    = rgb($danger_hex)
HYPR_EOF
  log "Rendered Hyprland palette → $out"
}

reload_hyprland() {
  if command -v hyprctl > /dev/null 2>&1; then
    if hyprctl version > /dev/null 2>&1; then
      if hyprctl reload; then
        log "Reloaded Hyprland"
      else
        log_err "Failed to reload Hyprland"
      fi
    else
      log "Hyprland not running – skipping reload"
    fi
  else
    log "hyprctl not found – skipping Hyprland reload"
  fi
}
