# palette-switch module: neovim
# Rendered and sourced automatically by palette-switch.
# Note: no corresponding NixOS module option; always deployed when
# palette-switcher is enabled.

PALETTE_SWITCH_RENDERERS+=(neovim)

render_neovim() {
  load_palette
  local out="$HOME/.config/nvim/lua/palette-colors.lua"
  mkdir -p "$(dirname "$out")"
  cat > "$out" <<LUA_EOF
-- Generated by palette-switch – do not edit by hand
-- Add  require('palette-colors').apply()  to your init.lua to use these colors
local M = {}

M.colors = {
  bg           = "$bg",
  programBg    = "$programBg",
  fg           = "$fg",
  primary      = "$primary",
  secondary    = "$secondary",
  tertiary     = "$tertiary",
  accent       = "$accent",
  danger       = "$danger",
  warning      = "$warning",
  success      = "$success",
  info         = "$info",
  black        = "$black",
  dark         = "$dark",
  muted        = "$muted",
  light        = "$light",
  white        = "$white",
}

function M.apply()
  local c = M.colors
  vim.api.nvim_set_hl(0, "Normal",      { fg = c.fg,      bg = c.bg })
  vim.api.nvim_set_hl(0, "NormalFloat", { fg = c.fg,      bg = c.programBg })
  vim.api.nvim_set_hl(0, "Comment",     { fg = c.muted,   italic = true })
  vim.api.nvim_set_hl(0, "Keyword",     { fg = c.primary, bold   = true })
  vim.api.nvim_set_hl(0, "Function",    { fg = c.secondary })
  vim.api.nvim_set_hl(0, "String",      { fg = c.success })
  vim.api.nvim_set_hl(0, "Number",      { fg = c.warning })
  vim.api.nvim_set_hl(0, "Error",       { fg = c.danger,  bold   = true })
  vim.api.nvim_set_hl(0, "StatusLine",  { fg = c.fg,      bg = c.dark })
  vim.api.nvim_set_hl(0, "LineNr",      { fg = c.muted })
  vim.api.nvim_set_hl(0, "CursorLine",  { bg = c.dark })
  vim.api.nvim_set_hl(0, "Visual",      { bg = c.muted })
  vim.api.nvim_set_hl(0, "Pmenu",       { fg = c.fg,      bg = c.programBg })
  vim.api.nvim_set_hl(0, "PmenuSel",    { fg = c.bg,      bg = c.primary })
end

return M
LUA_EOF
  log "Rendered Neovim palette → $out"
}

reload_neovim() {
  local reloaded=0
  for sock in /tmp/nvim*.sock /run/user/"$(id -u)"/nvim*.sock; do
    [[ -S "$sock" ]] || continue
    if nvim --server "$sock" \
         --remote-send ':lua pcall(function() require("palette-colors").apply() end)<CR>'; then
      reloaded=$((reloaded + 1))
    else
      log_err "Failed to signal Neovim socket: $sock"
    fi
  done
  if [[ $reloaded -gt 0 ]]; then
    log "Signaled $reloaded Neovim instance(s)"
  else
    log "No running Neovim instances found"
  fi
}
