# palette-switch module: waybar
# Rendered and sourced automatically by palette-switch.

PALETTE_SWITCH_RENDERERS+=(waybar)

render_waybar() {
  load_palette
  local css_dir="$HOME/.config/waybar"
  mkdir -p "$css_dir"
  cat > "$css_dir/normal-style.css" <<CSS_EOF
/* Generated by palette-switch – do not edit by hand */

window#waybar {
  background-color: $bg;
  color: $fg;
  border: 5px solid $primary;
  border-top: hidden;
  border-radius: 0px 0px 30px 30px;
}

box {
  transition: 1s;
  margin-top: 0px;
}

label.module {
  margin: 10px 10px;
  transition: 1s;
}

#custom-spacer {
  padding: 0px 30px;
}

@keyframes drop {
  from { margin-top: 0; }
  to   { margin-top: 300px; }
}

.module {
  margin-top: 0px;
  animation: 0.05s linear drop;
  background-color: $secondary;
}
CSS_EOF
  log "Rendered Waybar CSS → $css_dir/normal-style.css"

  # Ensure style.css points somewhere sensible
  local style="$css_dir/style.css"
  local moved="$css_dir/moved-style.css"
  if [[ -L "$style" && "$(readlink "$style")" == *"moved-style.css"* && -e "$moved" ]]; then
    : # keep pointing at moved-style.css
  else
    ln -sf "$css_dir/normal-style.css" "$style"
  fi
}

reload_waybar() {
  if pgrep -x waybar > /dev/null 2>&1; then
    if pkill -SIGUSR2 waybar; then
      log "Reloaded Waybar"
    else
      log_err "Failed to signal Waybar"
    fi
  else
    log "Waybar not running – skipping reload"
  fi
}
