# palette-switch module: wofi
# Rendered and sourced automatically by palette-switch.

PALETTE_SWITCH_RENDERERS+=(wofi)

render_wofi() {
  load_palette
  local css_dir="$HOME/.config/wofi"
  mkdir -p "$css_dir"
  cat > "$css_dir/style.css" <<CSS_EOF
/* Generated by palette-switch – do not edit by hand */

@keyframes pri-sec-gradient-bg {
  0% {
    background-color: $primary;
  }
  50% {
    background-color: $secondary;
  }
  100% {
    background-color: $primary;
  }
}

window {
  background-color: $programBg;
  color: $fg;
  border: 3px solid $primary;
  border-radius: 12px;
  padding: 10px;
}

#input {
  background-color: $programBg;
  color: $fg;
  border: 3px solid $primary;
  border-radius: 8px;
  padding: 6px;
}

#entry:selected {
  color: $programBg;
  animation: 6s infinite linear pri-sec-gradient-bg;
  transition: background-color 0.5s ease;
}

#entry {
  padding: 4px 6px;
  background-color: transparent;
}
CSS_EOF
  log "Rendered Wofi CSS → $css_dir/style.css"
}
