{
  config,
  pkgs,
  lib,
  ...
}:

let
  cfg = config.modules.window-managers.hyprland;
in
{
  imports = [
    ./configuration/bindings.nix
    ./configuration/exec.nix
    ./configuration/dropdownTerm.nix
    ./configuration/workspace.nix
  ];
  config = lib.mkIf cfg.enable {

    wayland.windowManager.hyprland = {
      enable = true;
      configType = "hyprlang";
      settings = {
        # Source the runtime palette variables (generated by palette-switch).
        # Variables like $palettePrimary are available for use in hyprland configs.
        # Dummy variables to pacify the build validator

        "$mod" = "SUPER";
        "$terminal" = "ghostty";

        misc = {
          "disable_splash_rendering" = "true";
          "disable_hyprland_logo" = "true";
          "vfr" = "true";
        };

        # Propagate cursor theme to every process Hyprland spawns, including
        # XWayland clients such as VSCode.  Without these, XWayland apps can't
        # find the generated theme and fall back to the system default.
        # ELECTRON_OZONE_PLATFORM_HINT=auto makes Electron apps (VSCode, etc.)
        # prefer the native Wayland backend over XWayland, so they use the
        # compositor's cursor directly instead of relying on X11 cursor lookup.
        # XCURSOR_PATH ensures both the legacy ~/.icons and the XDG
        # ~/.local/share/icons paths are searched – Chromium/Electron uses its
        # own cursor lookup that does NOT fall back to XDG paths by default.
        env =
          lib.optionals config.modules.themes.xcursor.enable [
            "XCURSOR_THEME,palette-cursor"
            "XCURSOR_SIZE,${toString config.modules.themes.xcursor.size}"
            "XCURSOR_PATH,$HOME/.icons:$HOME/.local/share/icons:/usr/share/icons"
          ]
          ++ [
            "ELECTRON_OZONE_PLATFORM_HINT,auto"
          ];

        monitor = [
          "eDP-1, 1920x1200, auto, 1"
          ", preffered, auto, 1"
        ];

        workspace = [

        ]
        ++ (builtins.concatLists (
          builtins.genList (
            i:
            let
              ws = i + 1;
            in
            [
              "${toString i}"
            ]
          ) 9
        ));

        # Visual shit
        general = {
          # "col.active_border" = "$palettePrimary $paletteSecondary 45deg";
          # "col.inactive_border" = "$paletteMuted";
        };

      };
      extraConfig = ''
        # Step A: Provide dummy fallbacks so the Nix validator doesn't crash during build
        $palettePrimary = rgb(ffffff)
        $paletteSecondary = rgb(ffffff)
        $paletteMuted = rgb(888888)

        # Step B: Source the live theme (this overwrites the dummies at runtime)
        source = ~/.config/hypr/palette-colors.conf

        # Step C: Apply the colors to the borders AFTER the live theme is loaded
        general {
            col.active_border = $palettePrimary $paletteSecondary 45deg
            col.inactive_border = $paletteMuted
        }
      '';

    };
  };
}
