{ config, pkgs, lib, ... }:

let cfg = config.modules.terminals.ghostty;
in lib.mkIf cfg.enable {
  programs.ghostty = {
    enable = true;
    settings = {};  # Clear existing settings
  };

  # Static Ghostty config that includes a runtime-generated colors file.
  # Colors are managed by palette-switch; run `palette-switch apply` to
  # (re-)generate ~/.config/ghostty/colors.conf after switching palettes.
  home.file.".config/ghostty/config".text = ''
    # Runtime palette colors – generated by palette-switch
    config-file = ~/.config/ghostty/colors.conf
  '';
}
